### PR TITLE
feat(core-decorative-icon): changed css for ie11 browser

### PR DESCRIPTION
**Pull request by sudhirraivns0103**
Changed in styled component for fix IE11 browser issue
Closes #1477

### CODE REVIEW

**Comment by sudhirraivns0103** [comment]
embargo approval: https://services.trlcloud.com/prod/requestStatus/index.html?id=381991447

**Comment by jraff** [comment]
@sudhirraivns0103 E2E tests are failing, can you please investigate as to why.

**Comment by sudhirraivns0103** [comment]
Hi @jraff, 
I looked E2E test failed because screenshots match failed for browser list. I am trying to update the chrome_78, firefox_70.png... screenshot by npm run test:e2e but it is showing error.
Can you suggest to me how can I update the e2e test screenshot?

**Comment by jraff** [comment]
@sudhirraivns0103 Can this PR be closed?

**Comment by jraff** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
