### PR TITLE
style(core-css-reset): mixin to keep the global footer at the bottom of the viewport

### PR DESCRIPTION
**Pull request by smm-telus**
## Related issues

See #860

## Description

- Added `flex-main` mixin to align `footer` to bottom of viewport

## Checklist before submitting pull request

- [x] New code is unit tested
- Commits follow our [Developer Guide](https://tds.telus.com/contributing/developer-guide.html#make-a-commit)
- [x] For code changes, run `yarn prepr` locally
  - make sure visual and accessibility tests pass

### CODE REVIEW

**Comment by marcod1419** [comment]
Thanks for the PR @smm-telus! We'll review it as soon as we are able.

**Comment by theetrain** [comment]
Thanks for your contribution! The mixin itself is great, all it needs is some documentation added to [CssReset.md](https://github.com/telus/tds-core/blob/e0b0e462b584085b24a6c70f31f40dcdeef4c79d/packages/css-reset/CssReset.md). Perhaps a new 'Mixins' section along with a code sample.

**Comment by smm-telus** [comment]
@theetrain Updated

**Comment by jraff** [comment]
Closed, see https://github.com/telus/tds-core/pull/955

**Pull request closed without merging**
